export const PATH = {
  maintenance: '/maintenance',
  nonSpecificError: '/service-unavailable',
  notFoundError: '/not-found',
  main: '/',
  project: '/project',
  jeckathon: '/jeckathon',
  activity: '/activity',
  apply: '/apply',
  faq: '/faq',
  signup: '/apply/signup',
  login: '/apply/login',
  resetPin: '/apply/reset-pin',
  applicantInfo: '/apply/applicant-info',
  applyRegistration: '/apply/registration',
  applyComplete: '/apply/complete',
} as const;
