export const SNACKBAR_DEFAULT_DURATION = 4000;

export const SNACKBAR_ANIMATION_DURATION_TOKEN = {
  ENTER: "250",
  EXIT: "200",
} as const;

export const SNACKBAR_ANIMATION_TIMER = {
  ENTER: Number(SNACKBAR_ANIMATION_DURATION_TOKEN.ENTER),
  EXIT: Number(SNACKBAR_ANIMATION_DURATION_TOKEN.EXIT),
} as const;

export const SNACKBAR_QUEUE_FALLBACK_TIMEOUT = 1500;
