export const TOAST_DEFAULT_DURATION = 2500;

export const TOAST_ANIMATION_DURATION_TOKEN = {
  ENTER: "250",
  EXIT: "200",
} as const;

export const TOAST_ANIMATION_TIMER = {
  ENTER: Number(TOAST_ANIMATION_DURATION_TOKEN.ENTER),
  EXIT: Number(TOAST_ANIMATION_DURATION_TOKEN.EXIT),
} as const;

export const TOAST_QUEUE_FALLBACK_TIMEOUT = 1500;

export const TOAST_QUEUE_LIMIT = 3;
