export const API_ENDPOINT = {
  miniStudy: "/ministudies",
  jectalk: "/jectalks",
  sendEmailAuthCode: "/email/send/auth",
  verifyEmailCode: "/auth/code",
  pinLogin: "/auth/login/pin",
  checkEmailExists: "/auth/login/exist",
  memberProfileInitial: "/members/profile/initial",
  memberProfileInitialStatus: "/members/profile/initial/status",
  registerMember: "/members",
  resetPin: "/members/pin",
  refreshToken: "/auth/refresh",
  uploadPortfolio: "/upload/portfolios",
  question: "/apply/questions",
  draft: "/apply/temp",
  submitAnswer: "/apply/submit",
  projectReview: "/reviews",
  projectList: "/projects",
  projectDetail: "/projects/:projectId",
  semesters: "/semesters",
  applyStatus: "/apply/status",
} as const;
