export const API_ENDPOINT = {
  miniStudy: "/ministudies",
  jectalk: "/jectalks",
  sendEmailAuthCode: "/email/send/auth",
  verifyEmailCode: "/auth/code",
  checkEmailExists: "/auth/login/exist",
  applyMember: "/applicants/apply",
  memberMe: "/applicants/me",
  memberProfileInitialStatus: "/applicants/profile/initial/status",
  pinLogin: "/auth/login/pin",
  registerMember: "/applicants/apply",
  resetPin: "/applicants/pin",
  refreshToken: "/auth/refresh",
  uploadPortfolio: "/upload/portfolios",
  uploadContent: "/upload/contents",
  question: "/apply/questions",
  applyProfile: "/apply/profile",
  draft: "/apply/temp",
  submitAnswer: "/apply/submit",
  projectReview: "/reviews",
  projectList: "/projects",
  projectDetail: "/projects/:projectId",
  semesters: "/semesters",
  applyStatus: "/apply/status",
} as const;
