export const PATH = {
  maintenance: "/maintenance",
  nonSpecificError: "/service-unavailable",
  notFoundError: "/not-found",
  main: "/",
  project: "/project",
  jeckathon: "/jeckathon",
  activity: "/activity",
  apply: "/apply",
  faq: "/faq",
  applyGuide: "/apply/guide",
  applyFunnel: "/apply/funnel",
  applyContinue: "/apply/continue",
  resetPin: "/auth/reset-pin",
} as const;
