export const PATH = {
  maintenance: "/maintenance",
  nonSpecificError: "/service-unavailable",
  notFoundError: "/not-found",
  main: "/",
  project: "/project",
  jeckathon: "/jeckathon",
  activity: "/activity",
  apply: "/apply",
  applyList: "/apply/list",
  faq: "/faq",
  applyGuide: "/apply/guide",
  applyFunnel: "/apply/funnel",
  applyContinue: "/apply/continue",
  resetPin: "/auth/reset-pin",
  // 새로 추가된 페이지 경로입니다.
  landing: "/",
  vision: "/vision",
  teamProject: "/team-projects",
  miniStudy: "/mini-study",
  liveSession: "/live-session",
} as const;
